#!/bin/bash
source framework/install

if [[ ! -f easymark.tar ]]; then
	tput setaf 1
	echo "easymark.tar is not present - nothing to deploy"
	exit 1
else
	has_changed=0
	hash="$(sha256sum easymark.tar)"
	if [[ ! -f .last-deployment-hash ]]; then
		has_changed=1
	else
		last_hash="$(cat .last-deployment-hash)"
		[[ "$hash" != "$last_hash" ]] && has_changed=1
	fi
	if [[ $has_changed -ne 0 ]]; then
		print_changed "EasyMark binary has changed - updating..."

		rm -rf /usr/local/lib/easymark
		mkdir -p /usr/local/lib/easymark
		tar -xf easymark.tar -C /usr/local/lib/easymark
		mv /usr/local/lib/easymark/easymark-*/* /usr/local/lib/easymark
		rmdir /usr/local/lib/easymark/easymark-*

		echo "$hash" > .last-deployment-hash
	else
		echo "EasyMark binary is installed"
	fi

	ln -sf /usr/local/lib/easymark/bin/easymark /usr/local/bin/easymark
	mkdir -p /var/lib/easymark

	etc/easymark.service > .tmp-easymark-service
	if differ .tmp-easymark-service /etc/systemd/system/easymark.service; then
		print_changed "EasyMark unit file has changed - updating..."
		cp .tmp-easymark-service /etc/systemd/system/easymark.service
		systemctl daemon-reload
		systemctl stop easymark.service
	else
		echo "EasyMark unit file hasn't changed"
	fi
	rm .tmp-easymark-service

	echo -n "easymark.service "
	if ! systemctl is-active easymark; then
		print_changed "EasyMark service is not active - starting..."
		systemctl start easymark
	fi

	echo -n "easymark.service "
	if ! systemctl is-enabled easymark; then
		print_changed "EasyMark service is not enabled on startup - enabling..."
		systemctl enable easymark
	fi
fi
