#!/bin/bash
set -euo pipefail
source framework/install
source .env

group_exists smtp
user_exists smtp \
	--system \
	--gid smtp \
	--create-home \
	--home-dir /var/lib/smtp \
	--shell /usr/sbin/nologin

NETRC_FILE=/var/lib/smtp/.netrc
echo "machine $SMTP_HOST
login $SMTP_USERNAME
password $SMTP_PASSWORD
" > $NETRC_FILE
chown smtp:smtp $NETRC_FILE
chmod u=r,og= $NETRC_FILE
