#!/bin/bash
source framework/install
[[ -f .env ]] && source .env

# Section headers
H_ROOT_SECTION="9;Root Section"
H_APT_PACKAGES="3;APT Packages"
H_EASYMARK="4;EasyMark"
H_STARTUP_SERVICES="3;Startup Services"
H_DOTFILES="13;Dotfiles"

print_header $H_ROOT_SECTION
	
if [[ $EUID -eq 0 ]]; then
	ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime

	print_header $H_APT_PACKAGES
	modules/autoinstall
	print_footer $H_APT_PACKAGES

	print_header $H_EASYMARK
	modules/easymark
	print_footer $H_EASYMARK

	print_header $H_STARTUP_SERVICES
	modules/sudoers

	echo "Locking root..."
	passwd -l root

	chsh -s /usr/bin/fish admin

	modules/autoupgrade
	print_footer $H_STARTUP_SERVICES
else
	echo "Not executing root section - not root"
fi

print_footer $H_ROOT_SECTION


print_header $H_DOTFILES
cp_dot config.fish .config/fish/config.fish
cp_dot gitconfig .gitconfig
print_footer $H_DOTFILES
