#!/bin/bash
source framework/install
[[ -f .env ]] && source .env

# Section headers
H_ROOT_SECTION="9;Root Section"
H_APT_PACKAGES="3;APT Packages"
H_STARTUP_SERVICES="3;Startup Services"
H_DOTFILES="13;Dotfiles"

print_header $H_ROOT_SECTION
	
if [[ $EUID -eq 0 ]]; then
	print_header $H_APT_PACKAGES
	modules/autoinstall
	print_footer $H_APT_PACKAGES
	
	print_header $H_STARTUP_SERVICES
	modules/sudoers
	chsh -s /usr/bin/fish admin
	print_footer $H_STARTUP_SERVICES
else
	echo "Not executing root section - not root"
fi

print_footer $H_ROOT_SECTION


print_header $H_DOTFILES
cp_dot config.fish .config/fish/config.fish
print_footer $H_DOTFILES
