#!/bin/sh

# houly, daily etc.
level="$1"
storage_class="$2"
backup_folder="${level}_$(date +%F_%H:%M:%S)"

tar cf /home/backup-gcp/caddy.tar /var/lib/caddy/.local/share/caddy
sudo -u backup-gcp sh -c "
gsutil cp -s $storage_class /var/lib/easymark/database.json \"gs://em_veskur_backups/$backup_folder/\"
gsutil mv -s $storage_class ~/caddy.tar \"gs://em_veskur_backups/$backup_folder/\"
"
