#!/bin/bash
source .env
MISC_FILES_DIR=/var/lib/regular-logwatch

echo "=====
BEGIN of run on $(date)

"

last_run_time="3 days ago"
if [[ -f $MISC_FILES_DIR/last-run-time ]]; then
	last_run_time="$(head -c -1 < $MISC_FILES_DIR/last-run-time)"
fi
echo "Last run time: $last_run_time
---"

# last run time is captured before logwatch is run so that there
# is no possibility for a gap
new_last_run_time="$(date)"


function improve_logwatch_css {
	sed 's/font-size: 10px/font-size: 1.2em; color: black; line-height: .75em/' \
		| sed 's/background: #6D88AD/background: #dedede/' \
		| sed 's/}/} * {border: none;}/'
}

function split_html_lines {
	# to avoid exceeding line length limits in email firewalls
	sed -E 's/&nbsp;|>/\0\n/g'
}

function trim_leading_space {
	sed -E 's/^\s+//g'
}

echo "
Logwatch output
---
"
mp_boundary="multipart-boundary-$(base64 < /dev/urandom | head -c 5)"
mail="From: \"EasyMark\" <$LOGWATCH_EMAIL_SENDER_ADDRESS>
To: \"$LOGWATCH_EMAIL_RECIPIENT_NAME\" <$LOGWATCH_EMAIL_RECIPIENT_ADDRESS>
Subject: Logwatch-Report
MIME-Version: 1.0
Content-Type: multipart/alternative;boundary="$mp_boundary"

--$mp_boundary
Content-Type: text/plain;charset=\"utf-8\"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline


$(logwatch --range "since $last_run_time" \
	--detail med \
	| unix2dos)

--$mp_boundary
Content-Type: text/html;charset=\"utf-8\"
Content-Transfer-Encoding: quoted-printable
Content-Disposition: inline

$(logwatch --range "since $last_run_time" \
	--format html \
	--detail med \
	| split_html_lines \
	| trim_leading_space \
	| improve_logwatch_css \
	| grep . \
	| unix2dos)

--$mp_boundary--

"


echo "
cURL output
---
"
echo "$mail" | sudo -u smtp curl \
	--ssl-reqd smtp://$SMTP_HOST:$SMTP_PORT \
	--mail-from $LOGWATCH_EMAIL_SENDER_ADDRESS \
	--mail-rcpt $LOGWATCH_EMAIL_RECIPIENT_ADDRESS \
	--upload-file - \
	--netrc \
	--verbose


# For debugging
echo "$mail" > $MISC_FILES_DIR/last-sent-message
chmod u=rw,og= $MISC_FILES_DIR/last-sent-message


if [[ "$1" = "--set-last-run-time" ]]; then
	echo "---

	Recording last run time"
	echo "$new_last_run_time" > $MISC_FILES_DIR/last-run-time
	chmod u=rw,og= $MISC_FILES_DIR/last-run-time
fi
