#!/bin/sh
curl "https://caddyserver.com/api/download?os=linux&arch=amd64" -o /tmp/caddy
chmod +x /tmp/caddy
systemctl stop caddy.service
mv /tmp/caddy /usr/local/bin/caddy
systemctl start caddy.service
