#!/bin/sh
curl "https://caddyserver.com/api/download?os=linux&arch=amd64" -o /tmp/caddy
chmod +x /tmp/caddy
[[ -f /etc/systemd/system/caddy.service ]] && systemctl stop caddy.service
mv /tmp/caddy /usr/local/bin/caddy
[[ -f /etc/systemd/system/caddy.service ]] && systemctl start caddy.service
